#-*- coding:utf-8 -*-

REDIS_HOST = "127.0.0.1"
REDIS_PASSWORD = None
REDIS_PORT = 6379
REDIS_KEY = 'proxies'
DEFAULT_SCORE = 10
MAX_SCORE = 100
MIN_SCORE = 0

POOL_UPPER_THRESHOLD = 10000
TEST_URL = 'http://www.baidu.com'
VALUE_CODE = [200]
BATCH = 10

TEST_CYCLE_TIME = 10

CRAWL_CYCLE_TIME = 30

TESTER_ENABLED = True
GETTER_ENABLED = True
API_ENABLED = True

